### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosipy#251]
Compilations of issues found during COSIfest

**Comment by ckierans** [comment]
I already had cosipy installed, but I tried to update it with
$ git pull
$ pip install -e .

But got the following error:

```
Obtaining file:///Users/ckierans/Software/COSItools/COSItools/cosipy
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running egg_info
      creating /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info
      writing /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info/entry_points.txt
      writing requirements to /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info/requires.txt
      writing top-level names to /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info/top_level.txt
      writing manifest file '/private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-pip-egg-info-d51qfto3/cosipy.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/ckierans/Software/COSItools/COSItools/cosipy/setup.py", line 19, in <module>
          setup(name='cosipy',
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 545, in run
          self.prune_file_list()
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/command/sdist.py", line 161, in prune_file_list
          super().prune_file_list()
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 392, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/Users/ckierans/Software/COSItools/COSItools/python-env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```


I didn't dive in since my jupyter notebooks for the tutorials ran through with no problem.

**Comment by israelmcmc** [comment]
Since there was only a single problem listed, I'm changing this issue to be specific. I added it to the more general [installation](https://github.com/cositools/cosipy/issues?q=state%3Aopen%20label%3A%22installation%22) label.

**Comment by israelmcmc** [comment]
@ckierans do you still see this issue? If so, can you please check what you have in this file:
https://github.com/cositools/cosipy/blob/develop/cosipy/_version.py

I think the error points to an issue with the version format, which has been changing a lot.

**Comment by ckierans** [comment]
I still do see this error. This is for main branch. And I have __version__ = "0.3.4" in the version.py file. Let me know if I can provide any more info to help.

**Comment by israelmcmc** [comment]
Thanks for checking, @ckierans.

I found some similar issues because of version conflicts: https://stackoverflow.com/questions/79252233/canonicalize-versionversion-strip-trailing-zero-false-while-doing-colcon-buil

@ckierans Can you please try: `pip install --upgrade packaging` followed by `pip install -e .`. And if that doesn't work, then maybe with `pip install setuptools==68`

**Comment by ckierans** [comment]
The --upgrade packaging gave me:

```
Requirement already satisfied: packaging in /Users/ckierans/miniforge3/lib/python3.12/site-packages (24.1)
Collecting packaging
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Downloading packaging-25.0-py3-none-any.whl (66 kB)
Installing collected packages: packaging
  Attempting uninstall: packaging
    Found existing installation: packaging 24.1
    Uninstalling packaging-24.1:
      Successfully uninstalled packaging-24.1
Successfully installed packaging-25.0
```

and then trying pip install -e . after still gives an error. Note the error below is different than the original error posted above. When I ran git pull; pip install -e . yesterday, I actually saw this error below, not the previous one (sorry, didn't realize until now). So it looks like something has changed becuase it's now getting stuck in astromodels instead of the first setup.py step.

```
Obtaining file:///Users/ckierans/Software/COSItools/COSItools/cosipy
  Preparing metadata (setup.py) ... done
Collecting histpy<2 (from cosipy==0.3.4)
  Using cached histpy-1.1.4-py3-none-any.whl.metadata (979 bytes)
Collecting mhealpy (from cosipy==0.3.4)
  Using cached mhealpy-0.3.6-py3-none-any.whl.metadata (757 bytes)
Collecting scoords (from cosipy==0.3.4)
  Using cached scoords-0.0.2-py3-none-any.whl.metadata (2.9 kB)
Collecting astromodels>=2.4.2 (from cosipy==0.3.4)
  Using cached astromodels-2.4.3.tar.gz (2.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/setup.py:54: SyntaxWarning: invalid escape sequence '\.'
        tokens = re.findall("lib(.+)(\.so|\.dylib|\.a)(.+)?", lib_name)
      /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/setup.py:157: SyntaxWarning: invalid escape sequence '\-'
        if re.match(f"lib{library_root}[\-_\.]([0-9])*\d*(\.[0-9]\d*)*", os.path.basename(result)) is None:
      /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/versioneer.py:423: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/setup.py:222: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        xspec_version = LooseVersion(xspec_raw_version)
      /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/setup.py:226: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if xspec_version < LooseVersion("12.9.0"):
      /private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/setup.py:241: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if xspec_version >= LooseVersion(version):
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/setup.py", line 398, in <module>
          ext_modules_configuration = setup_xspec()
                                      ^^^^^^^^^^^^^
        File "/private/var/folders/lw/vw1sthdx6m74z011lrt83qjm50hhbv/T/pip-install-jrlyjdro/astromodels_6352c0d897cd412486db07d698726b89/setup.py", line 310, in setup_xspec
          raise IOError("Could not find library %s. Impossible to compile Xspec" % lib_root)
      OSError: Could not find library XSFunctions. Impossible to compile Xspec
      WARN: You have not specified and XSPEC version with the
      WARN: environment variable ASTRO_XSPEC_VERSION
      WARN: we will assume you have 12.12.1
      [('XSPEC_12_9_0', None), ('XSPEC_12_9_1', None), ('XSPEC_12_10_0', None), ('XSPEC_12_10_1', None), ('XSPEC_12_11_0', None), ('XSPEC_12_11_1', None), ('XSPEC_12_12_0', None), ('XSPEC_12_12_1', None)]
      
       Xspec is detected. Will compile the Xspec extension.
      
      
       NOTICE!!!!!
      
      If you have issues, manually set the ENV variable XSPEC_INC_PATH
      To the location of the XSPEC headers
      
      
      If you are still having issues, unset HEADAS before installing and contact the support team
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

pip install setuptools==68 was succesful:

```
Collecting setuptools==68
  Downloading setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
Downloading setuptools-68.0.0-py3-none-any.whl (804 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.0/804.0 kB 10.2 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 73.0.1
    Uninstalling setuptools-73.0.1:
      Successfully uninstalled setuptools-73.0.1
Successfully installed setuptools-68.0.0
```

But running pip install -e . afterwards results in the same error above in astromodels.

**Comment by israelmcmc** [comment]
@ckierans Good, I think the error you are getting now should go away if you run `unset HEADAS ASTRO_XSPEC_VERSION` before running `pip install -e .`

**Comment by ckierans** [comment]
You're right! That worked! Thanks, Israel :D

**Comment by israelmcmc** [comment]
Great! No problem. 

I'm closing this issue since
* canonicalize_version was like caused by a version of setuptools incompatible with packaging, and therefore it's independent of cosipy. I changed the label to "dependencies"
* The HEADAS error is a known issue, and it's in our troubleshooting already. It's independent of the original issue in this thread.
